# Generated by Django 4.0.5 on 2022-06-19 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_rename_images_product_image_remove_product_category_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='category',
            new_name='categories',
        ),
    ]
